//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public int IdRecipe { get; set; }
        public byte[] ImageRecipe { get; set; }
        public string NameRecipe { get; set; }
        public string Ingredient { get; set; }
        public string Description { get; set; }
        public bool Moder { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public Nullable<int> IdMeal { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Meal Meal { get; set; }
        public virtual Users Users { get; set; }
    }
}
