//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopCook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meal()
        {
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int IdMeal { get; set; }
        public byte[] ImageMeal { get; set; }
        public string NameMeal { get; set; }
        public string DescriptionMeal { get; set; }
        public int IdCategory { get; set; }

        public Meal(string NameMeal, string DescriptionMeal, byte[] ImageMeal, int IdCategory)
        {
            this.NameMeal = NameMeal;
            this.DescriptionMeal = DescriptionMeal;
            this.ImageMeal = ImageMeal;
            this.IdCategory = IdCategory;
        }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}
